---
platform: linux
image_resource:
  type: docker-image
  source: {repository: node, tag: "6"}
image_resource:
  type: docker-image
  source: {repository: busybox}
inputs:
- name: repo
run:
  path: repo/src/pipeline/scripts/install.sh
